apiVersion: v2
name: justgate
description: justgate – multi-tenant observability proxy with admin UI
type: application
version: 1.0.8
appVersion: "1.0.8"

dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
