apiVersion: v1
kind: Secret
metadata:
  name: {{ include "justgate.fullname" . }}-secrets
  labels:
    {{- include "justgate.labels" . | nindent 4 }}
type: Opaque
data:
  backendJwtSecret: {{ default (randAlphaNum 32) .Values.backend.jwtSecret | b64enc | quote }}
  nextauthSecret:   {{ default (randAlphaNum 32) .Values.frontend.nextauthSecret | b64enc | quote }}
  databaseUrl:      {{ include "justgate.databaseUrl" . | b64enc | quote }}
  {{- if .Values.frontend.oidc.issuer }}
  oidcClientId:     {{ .Values.frontend.oidc.clientId | b64enc | quote }}
  oidcClientSecret: {{ .Values.frontend.oidc.clientSecret | b64enc | quote }}
  {{- end }}
